Repository OCA/sale-prebook, pull requests merged in 2025-03, with the labels that each got.

#1 [14.0][ADD] sale_stock_prebook: Add process to prebook a sale order's stock
  sale_stock_prebook/README.rst
  sale_stock_prebook/__init__.py
  sale_stock_prebook/__manifest__.py
  sale_stock_prebook/hooks.py
  sale_stock_prebook/models/__init__.py
  sale_stock_prebook/models/report_stock_forecasted.py
  sale_stock_prebook/models/sale_order.py
  sale_stock_prebook/models/sale_order_line.py
  sale_stock_prebook/models/stock_location_route.py
  sale_stock_prebook/models/stock_move.py
  sale_stock_prebook/models/stock_rule.py
  sale_stock_prebook/readme/CONTRIBUTORS.rst
  sale_stock_prebook/readme/DESCRIPTION.rst
  sale_stock_prebook/readme/USAGE.rst
  sale_stock_prebook/static/description/index.html
  sale_stock_prebook/tests/__init__.py
  sale_stock_prebook/tests/common.py
  sale_stock_prebook/tests/test_sale_stock_prebook.py
  sale_stock_prebook/views/sale_views.xml
  sale_stock_prebook/views/stock_location_route_views.xml
  sale_stock_prebook_stock_available_to_promise_release/README.rst
  sale_stock_prebook_stock_available_to_promise_release/__init__.py
  sale_stock_prebook_stock_available_to_promise_release/__manifest__.py
  sale_stock_prebook_stock_available_to_promise_release/models/__init__.py
  sale_stock_prebook_stock_available_to_promise_release/models/sale.py
  sale_stock_prebook_stock_available_to_promise_release/models/stock_move.py
  sale_stock_prebook_stock_available_to_promise_release/readme/CONTRIBUTORS.rst
  sale_stock_prebook_stock_available_to_promise_release/readme/DESCRIPTION.rst
  sale_stock_prebook_stock_available_to_promise_release/static/description/index.html
  sale_stock_prebook_stock_available_to_promise_release/tests/__init__.py
  sale_stock_prebook_stock_available_to_promise_release/tests/test_sale_stock_prebook.py
  setup/.setuptools-odoo-make-default-ignore
  setup/README
  setup/sale_stock_prebook/odoo/addons/sale_stock_prebook
  setup/sale_stock_prebook/setup.py
  setup/sale_stock_prebook_stock_available_to_promise_release/odoo/addons/sale_stock_prebook_stock_available_to_promise_release
  setup/sale_stock_prebook_stock_available_to_promise_release/setup.py
Labels: bot is merging ⏳

#6 [16.0][MIG] sale_stock_prebook: Migrate from 14.0 to 16.0
  sale_stock_prebook/README.rst
  sale_stock_prebook/__init__.py
  sale_stock_prebook/__manifest__.py
  sale_stock_prebook/hooks.py
  sale_stock_prebook/models/__init__.py
  sale_stock_prebook/models/report_stock_forecasted.py
  sale_stock_prebook/models/sale_order.py
  sale_stock_prebook/models/sale_order_line.py
  sale_stock_prebook/models/stock_move.py
  sale_stock_prebook/models/stock_route.py
  sale_stock_prebook/models/stock_rule.py
  sale_stock_prebook/readme/CONTRIBUTORS.rst
  sale_stock_prebook/readme/DESCRIPTION.rst
  sale_stock_prebook/readme/USAGE.rst
  sale_stock_prebook/static/description/index.html
  sale_stock_prebook/tests/__init__.py
  sale_stock_prebook/tests/common.py
  sale_stock_prebook/tests/test_sale_stock_prebook.py
  sale_stock_prebook/views/sale_views.xml
  sale_stock_prebook/views/stock_route_views.xml
  setup/.setuptools-odoo-make-default-ignore
  setup/README
  setup/sale_stock_prebook/odoo/addons/sale_stock_prebook
  setup/sale_stock_prebook/setup.py
Labels: bot is merging ⏳, approved

#7 [PERF] sale_stock_prebook : Don't call cancel on empty recordset
  sale_stock_prebook/models/sale_order.py
Labels: bot is merging ⏳, approved

#8 [16.0][PERF] sale_stock_prebook : Don't call cancel on empty recordset
  sale_stock_prebook/models/sale_order.py
Labels: bot is merging ⏳

#3 [16.0] [IMP] sale_stock_prebook: Specific picking type for booking
  sale_stock_prebook/__manifest__.py
  sale_stock_prebook/models/stock_rule.py
  sale_stock_prebook/tests/common.py
  sale_stock_prebook/tests/test_sale_stock_prebook.py
  sale_stock_prebook/views/stock_rule_views.xml
Labels: enhancement, bot is merging ⏳

#4 [16.0][MIG] sale_stock_prebook_stock_available_to_promise_release
  sale_stock_prebook_stock_available_to_promise_release/README.rst
  sale_stock_prebook_stock_available_to_promise_release/__init__.py
  sale_stock_prebook_stock_available_to_promise_release/__manifest__.py
  sale_stock_prebook_stock_available_to_promise_release/models/__init__.py
  sale_stock_prebook_stock_available_to_promise_release/models/sale.py
  sale_stock_prebook_stock_available_to_promise_release/models/stock_move.py
  sale_stock_prebook_stock_available_to_promise_release/readme/CONTRIBUTORS.rst
  sale_stock_prebook_stock_available_to_promise_release/readme/DESCRIPTION.rst
  sale_stock_prebook_stock_available_to_promise_release/static/description/index.html
  sale_stock_prebook_stock_available_to_promise_release/tests/__init__.py
  sale_stock_prebook_stock_available_to_promise_release/tests/test_sale_stock_prebook.py
  setup/sale_stock_prebook_stock_available_to_promise_release/odoo/addons/sale_stock_prebook_stock_available_to_promise_release
  setup/sale_stock_prebook_stock_available_to_promise_release/setup.py
Labels: bot is merging ⏳
